### ISSUE TITLE
Set up QA server

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#10]
We need a publically available server for QA purposes.
Server should be linux with the mininal set up necessary 
  * SQL Server
  * Mysql server with legacy tasvideos data and automatic import on startup.

Need system for easily deploying the dev branch to this server.
Need to create dev branch

**Comment by adelikat** [comment]
Still todo:
1) prod server - Cron job that puts media files in a shared folder
2) prod server - Cron job that puts db backup in a shared folder
3) qa/demo server - bash script to pull latest and reboot
4) cron to auto run pull + reboot ?

**Comment by darkpsy3934** [comment]
Demo server is up and running.  Next step is to create the automatic imports using a non-resource intensive method.

Currently investigating this.

**Comment by adelikat** [comment]
We have full automation from prod to demo, which is the scope of this ticket. Closing :)
