### ISSUE TITLE
Script prism.js hurts page load times significantly

### ISSUE THREAD

**Issue by Masterjun3** [adelikat/tasvideos#1130]
Currently, prism.js is loaded on every page. It takes up a significant portion of the load time.
Blocking prism.js in my adblocker reduces loading time for forum page from 260ms to 190ms.

Example on /Forum page.
![image](https://user-images.githubusercontent.com/22375320/155859177-d6470080-66b1-48c4-8748-1e5942f4cac1.png)

**Comment by nattthebear** [comment]
It's needed on the forum, so nothing's wrong there.  It's also needed on the wiki, so what pages does that leave where we could remove it?  Not many.  We could give it a `defer` attribute I suppose.

**Comment by Masterjun3** [comment]
It's not needed on the forum.
It's not needed on the wiki.
It's only needed for *specific pages* on the forum and wiki.

It would leave rougly 98% of pages we could speed up. Is that not enough?

**Comment by adelikat** [comment]
It's only used in the wiki/forum for pages that contain markup for a code block? It could be that a script tag could be part of what the engine outputs in those situations? That's probably complicated though.

**Comment by nattthebear** [comment]
That's a massive amount of JS execution time on load, for sure.  Really disappointing performance.  We should investigate potential perf gains from using the [autoloader](https://prismjs.com/plugins/autoloader/), I think a lot of the cost is from loading all of those languages.
