### ISSUE TITLE
Ability to reset forum polls

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#117]
Occasionally polls need to be reset, we need a permission locked feature to do this

**Comment by vadosnaprimer** [comment]
Maybe admin should also be able to edit poll results, for cases when some vote is requested to be changed or gets invalidated?

**Comment by adelikat** [comment]
DUN.  To reset an individual vote, it is done on the vote results page (the user would need both the SeePollResults and the ResetPollResults permissions to do this)
