### ISSUE TITLE
implement the settableattributes module

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#132]
This might be a tricky one.  It affects the css of future markup.
http://tasvideos.org/TextFormattingRules/ListOfModules.html

**Comment by nattthebear** [comment]
That looks ugly.  Got an example of a page that uses it?  Are there any more stupid modules like that?

**Comment by nattthebear** [comment]
It honestly doesn't even feel like something that should be a module =/

**Comment by vadosnaprimer** [comment]
Example: http://tasvideos.org/Natt/YoutubeFormatList.html

**Comment by nattthebear** [comment]
Well, whoever made that page was a moron.

We can support this, of course, but to figure out best how it'll be helpful to know if there are any other modules that allow manual styling, and if there are any other "stateful" modules that affect future page rendering.

**Comment by adelikat** [comment]
DUN
