### ISSUE TITLE
implement the pubcounts module

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#134]
http://tasvideos.org/PubCounts.html

**Comment by adelikat** [comment]
https://github.com/adelikat/tasvideos/issues/135 really needs to be addressed first before doing this task

**Comment by adelikat** [comment]
Obsolete to /Activity page instead

**Comment by vadosnaprimer** [comment]
Activity doesn't show dates. It would be very useful to see them. Also it needs to link back to the user profile like judge activity does. And back to overall activity too?
