### ISSUE TITLE
Registration wrongfully claims password missmatch

### ISSUE THREAD

**Issue by Henny022** [adelikat/tasvideos#1361]
When trying to register the site claims the two entered passwords do not match, even though they are both the same copy and pasted password.
The password is randomly generated 128 characters.
The error message is `The password and confirmation password do not match.`
My guess is the actual error is either the length or the used characters.
Happens with:
- `SFcp&vSzHUH&Cw^aQWH@wSQV&ACKBdi6#*PxkmAy8LubnCcTZUg6CZ1nYi80s8*Nxm54M*S*cRZgh8fxIRP@Qnp2$d%6AZrCoD^IpN4T^7D05caCZ1AbxXZq5$IcbOVM`
- `vS@GSlkDcRFffp!Ok#5CI9uXgiIjH&T%hNa^GvkM@ITAq7lu0dDU%&st7Pb!r7IdgyNCFu6w1BF0pzwJs^ou!i3xPugov2K00H3yrl9UXiUOBVdXr!Sf!wCDQ1kzChFc`
- `4W#O3FcY!#NRVz5Td^b$Ck$p6451X!m&XnbencYAg76g1$^2wQZy!bmXfRLZIntQ^bH4QQ#7E0YhneEOZXx9YIM*g@k#zI3MA@Opc!HUD*&OPPn!HCNlFn8WGnsYR4sE`

Registration worked when I reduced the character count to 64.

**Comment by Henny022** [comment]
I just checked and that might really be the problem.
Password sets `data-val-length-min` and `data-val-length-max`, ConfirmPassword does not.

**Comment by Masterjun3** [comment]
Ideally the Password field shouldn't force a hard limit on the html side of things.
It's bad practice to truncate fields where you can't even see the input, especially when characters are often just pasted inside.

Without the `maxlength="100"` people would be able to actually see the error message in the image above.

**Comment by Henny022** [comment]
I agree, just cutting off someones password seems like a bad idea, especially in the age of password managers and randomly generated passwords that you just copy and paste.
I'll never know what my password actually is, and some inconsistencies in the login prompt could prevent me from ever logging into my account.

**Comment by Masterjun3** [comment]
Fixed by a40f9b57f9642a9ffc2a99f1e02bf0f65191a8ff.
