### ISSUE TITLE
Wiki Edits - handle concurrency

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#168]
https://www.youtube.com/watch?v=4kgILKQuGjk 

We can catch DbUpdateConcurrencyException for this.  But we need to handle it gracefully and pass the info back to the user.  Perhaps the one who loses the race can get some way to merge their changes with the newly saved revision. 3-way merge perhaps

**Comment by vadosnaprimer** [comment]
Any automated merge in this case is worse than just telling the user something like "While you've been editing, the page contents were changed by someone else (maybe you in another tab?). Here's the link to the latest version, please move your edits over." I see it as a warning that doesn't destroy the current edits you've made, it would just not reload the page. For 3-way merge it'd require a dedicated gui and conflict detector, which feels like an overkill. Unless we store wiki as git of course ;D

**Comment by adelikat** [comment]
For edits, we should pass the timestamp of the latest revision to the page and have it POST back.  Then we check the timestamp of the latest revision again.  If greater than the original, we pull show a model state error and pass back the newest revision.  Then we can display a side by side diff with what the user's edit
