### ISSUE TITLE
Unit tests for wiki parser

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#169]
We at least need a few to have a respectable engine.

**Comment by nattthebear** [comment]
They won't make it respectable ;p

I feel like baseline/snapshot tests would be pretty good here; cover a lot of ground with little effort.  Because there's no specification for how it should work, just what it does...

**Comment by nattthebear** [comment]
There's a bit of manual effort involved, but there are now snapshot tests of the wiki system.  Check out https://github.com/nattthebear/TASVideosWikiSnaps, and then run `WikiEngineTest` pointing at that with flags depending on what you're doing.
