### ISSUE TITLE
Publications - support multiple movie files

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#180]
Publication importer needs to import multiple movie files.
We need a new permission (admin only) and a ui that allows add/removing supplemental movie files.  The original file should not be able to be modified.

**Comment by adelikat** [comment]
Added import, display and ability to download these files.  Edit ability will be covered in #215

**Comment by vadosnaprimer** [comment]
We had a single case when there was some error and we had to replace the published movie file. As a last resort this probably should be possible, since how can it be fixed otherwise if not by hacking the db?
