### ISSUE TITLE
Automatic linking in wiki

### ISSUE THREAD

**Issue by nattthebear** [adelikat/tasvideos#195]
https://tasvideos.mistflux.net/4124S

I need to look at this on the live site (after it stops being offline).  The live site has links but they're broken, and the 2.0 site has no links.

**Comment by nattthebear** [comment]
Classic wiki autolinks things starting with http:// (and possibly some other affixes), new wiki does not.  Lots of questions on how to handle formatting, and whether much content needs it.  The linked page renders some autolinks in the old system but they're slightly broken (missing the hash part), yet no one cared or fixed it.

We'll see what pages need this sort of thing.

**Comment by adelikat** [comment]
I marked it as 2.0 Release because by then we should at least know what we want to do by then

**Comment by adelikat** [comment]
Closing this as a "won't fix"
1) The alternative is easy and intended.  The quick help on the edit form even mentions to use brackets for links
2) Supporting this would make the parser more cumbersome to work with
3) These links are easily fixed as we see them
4) Even if unfixed, a basic user can see the url and go to it if needed

Note: The example page has been fixed on the prod site and subsequently the demo
