### ISSUE TITLE
Forums - &quot;

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#202]
https://tasvideos.quantium.tk/Forum/Topics/14051

This page is a good example, as it happens in user signatures, as well as user location as well as posts.

Don't know if this is something that needs to be addressed at the database level, with a forum RenderHtml call, or razor Html.Raw, or something else entirely

**Comment by nattthebear** [comment]
Looking first at an excerpt from https://tasvideos.quantium.tk/Forum/Posts/345967#345967

Here's the raw text I see when I try to quote it, so I'm assuming this is what's in the DB:

```
The &quot;spirit&quot; of tool-assisted speedrunning
```

What are the values for enablehtml, enablebbcode on this post in the db?
