### ISSUE TITLE
Show Submission on submission topics

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#203]
THe old system would create a TVA post with the rendered wiki html baked into the post. For various technical reasons, there's no way to get baked html to look as expected in the new forum system.

There's a few potentially better alternatives anyway.

1) Put the submission forum thread directly into the Submissions/View page

2) Put the submission (in a miniature form or fixed size) directly in the forum topic

3) Simply have easy link back from the forum to the submission?

**Comment by vadosnaprimer** [comment]
It all looks like there should be a wiki-markup forum tag of some kind? Submission wiki text could the be put inside that tag in a forum post. Same for usefiles. No HTML involved.

**Comment by nattthebear** [comment]
That would make forum post rendering unavoidably dynamic; a forum post could contain a wiki segment which could contain a module.  This would have lots of future implications for https://github.com/adelikat/tasvideos/issues/129

It would also raise the complexity of forum parsing significantly.  Sure, it's easy to look for [wikicontent]...[/wikicontent] and then just run our existing wiki parser on the substring, but then we have to support all of that going forward.  It's also a lot less feasible to make breaking changes to forum rendering; with the wiki, at least the editor army can correct issues.

**Comment by nattthebear** [comment]
Perhaps this could be done directly in the razor.  If we have some special connection between topics and submissions, then the razor page for displaying a topic could just use a `<wiki-markup>` at the top of it

**Comment by adelikat** [comment]
The markup is a wiki page, and rendering a wiki page is pretty easy in razor: 
@await  Component.RenderWiki("InternalSystem/1000S")
