### ISSUE TITLE
Set up EF Migrations

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#210]
We want to use EF Migrations, right now we are blowing away the db, which is generally frowned upon for production systems.

I haven't set up anything until now since the schema is still changing.

The end result is I'd like to have a single "initial migration" for the go live date.  However, we want to set this up before then.  We can either squash migrations steps on go live date, or just build up some steps, and just let it be.

**Comment by nattthebear** [comment]
I'm not so concerned about how many migrations we have before live, but we definitely want to be using migrations and _testing the process of migration_ before live.

**Comment by adelikat** [comment]
Added the infrastructure for adding migrations, and the InitialCreate migration.  We aren't going to use migrations until after a go-live since the migration of existing data is so crucial.  There may need to be better infrastructure around this, maybe a bash script or something that makes adding migrations easier, and a dev site that is somehow using migrations AND periodically pulling prod data in, but we will have to cross that bridge when we get there.
