### ISSUE TITLE
Wiki Markup:  = at the beginning of protocol-based URLs

### ISSUE THREAD

**Issue by nattthebear** [adelikat/tasvideos#217]
The following markup on the old site:
```
[=http://www.speedtest.net/result/903855961.png|Speedtest.net result here]

[http://www.speedtest.net/result/903855961.png|Speedtest.net result here]
```
Generates the following HTML on the old site (p tags and other irrelevant stuff removed):
```
<img alt="" title="" class="embed" src="http://www.speedtest.net/result/903855961.png" width="300" height="135">

<img alt="" title="" class="embed" src="http://www.speedtest.net/result/903855961.png" width="300" height="135">
```

So the old site just eats and ignores the `=` at the beginning but generates the same output.

The new site does not do this at the moment.  It doesn't seem to be a needed syntax feature.  The only reason `=` exists is to disambiguate internal wiki links from some things that aren't links at all, but when the link starts with `http://` it's already unambiguously parsed as an external link.

We could replace all instances of `=http://` or `=https://` on import, or add the fix to MakeBracketed, or just ignore the whole thing as yet another useless mess syntax rule in the old wiki.

**Comment by nattthebear** [comment]
`/Encoders` (look at the inactive tab and the broken images there) is an example of this.

**Comment by nattthebear** [comment]
Per @vadosnaprimer , at some previous point in time this was related to #218 and somehow disambiguated that.  But that code seems to have been lost even in the old wiki.

**Comment by vadosnaprimer** [comment]
So this gets documented

18:29:46 <feos> working https://web.archive.org/web/20120808015751/http://tasvideos.org/SiteHistory/EncoderLogos.html
18:29:54 <feos> broken https://web.archive.org/web/20120908071243/http://tasvideos.org/SiteHistory/EncoderLogos.html
18:30:01 <feos> worker around https://web.archive.org/web/20121023211651/http://tasvideos.org/SiteHistory/EncoderLogos.html

**Comment by adelikat** [comment]
So, I manually fixed all current instances of this on the prod site, don't know if we still want to bother addressing this or not.

**Comment by nattthebear** [comment]
Very nice.  Best to save that reclaimed syntax space for #218.
