### ISSUE TITLE
Support bare anchor links

### ISSUE THREAD

**Issue by nattthebear** [adelikat/tasvideos#223]
Desired rendering (more or less):
```html
<a href=#foobar>baz</a>
```

Currently, neither `[#foobar]` nor `[=#foobar]` works for this.  `[=Full/Path/To/Page#foobar]` does work, but is maybe a bit awkward?

This doesn't work on the old site either.

**Comment by nattthebear** [comment]
Proposed syntax:
`[#foobar]`

This would be at lower priority than footnote links, which look like `[#2913]` (only digits allowed), so there'd be no loss of existing functionality there, nor would you be missing out on gained functionality -- the footnote feature actually uses the id `2913` in the above example, so the kind of link you would want in that case is always a footnote link and the id has already been used.

Right now, both the old and new wiki render `[#foobar]` as roughly `<a href="/#foobar">`, which takes you back to the front page of the site and then to `foobar` on there.  That's a mostly useless rendering, and in situations where you need it you can do `[=#foobar]` instead.

**Comment by nattthebear** [comment]
@vadosnaprimer No hurry but looking for an editor's perspective on this before I move to implementation.

**Comment by adelikat** [comment]
Looking at wiki orphans, it seems like the existing wiki pages are doing [=#foobar], what about those existing links?

**Comment by vadosnaprimer** [comment]
Is there an example page that had [=#foobar]? I'll check on waybackmachine if it ever used to work in some sane way.

**Comment by nattthebear** [comment]
There appear to be 5 instances of `[=#foobar]` in the old site, and 1 instance of `[#foobar]` in the old site, assuming everything is ending up on the wiki orphans page as I expect it to (it's bugged, so that all #links end up there).  You can see them at the very top of the page: https://tasvideos.quantium.tk/WikiOrphans

**Comment by vadosnaprimer** [comment]
As expected, those anchors were working in the past.
- [First snapshot with this anchor working](https://web.archive.org/web/20110807074106/http://tasvideos.org/GameResources/CommonTricks.html#AvoidingSaving).
- [First snapshot with it broken](https://web.archive.org/web/20130117234339/http://tasvideos.org/GameResources/CommonTricks.html#AvoidingSaving).

**Comment by nattthebear** [comment]
Thanks for the research.

Assuming this count is correct, we probably don't need to worry about backwards compat in any case.
