### ISSUE TITLE
Message judges when 72 hour window is up via PM

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#239]
We have this functionality in the legacy site.

If we add it here, give the user an option to opt out

**Comment by adelikat** [comment]
Throwing this out there, but what if this wasn't a go-live requirement? It requires some kind of cronjob, which I would rather not introduce.  And as a judge, these annoy me.

**Comment by MemoryTAS** [comment]
Honestly I never relied on these ever, I mainly looked at them to get the "unread messages" to go away.

**Comment by SamsaraTAS** [comment]
This is definitely not a requirement for me. It's a bit of an annoyance, I tend to actually wait out the 72 hour period before claiming things just to avoid it. Also, it's broken on me at least once before, leaving the workbench in an incredibly weird state while it fixes itself. I don't really think any of the judges use it, most judges take much longer than 3 days to judge something anyway.

(i also don't even like the 72 hour wait period as a whole but that's a different discussion)

**Comment by adelikat** [comment]
Masterjun, a former judge, also chimed in on the dislike for this feature.  Also, as a judge, I do not want this feature.

I'm going to just close this, rather than postpone it, since it seems clear that it simply isn't needed nor desired
