### ISSUE TITLE
_UserFilesInfo partial - show comments

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#241]
a userfile with comments: http://tasvideos.org/userfiles/info/57373143716900045

We need to show comments as part of this partial view

**Comment by vadosnaprimer** [comment]
Dunno if I mentioned but we definitely need a way to subscribe to those comments and be notified of new ones.

**Comment by adelikat** [comment]
That's a good idea, but needs to be a separate ticket.  Since that's an enhancement, and this is existing fucntionality that needs to be replicated
