### ISSUE TITLE
permission ViewPrivateUserData unused

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#273]
This was supposed to be used in user screens but is currently unused, not sure what happened there, but we do very much want to protected private data

**Comment by darkpsy3934** [comment]
What kind of data would be considered protected, other than Email?

**Comment by adelikat** [comment]
There's a banner on Users/Profile, and Profiles/User, that contains the email, email confirmed status, and locked out status
![Capture2](https://user-images.githubusercontent.com/1679846/90336913-89ef1880-dfa4-11ea-913a-581496ef4e02.PNG)

It should control this block.

Also, I guess it should also control the display of those fields on Users/Edit

**Comment by adelikat** [comment]
This was a false positive with resharper.  It is actually being used in the _Profile.cshtml file to restrict precisely that card
