### ISSUE TITLE
Wiki Edits - do not require message on HomePages

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#275]
We could do this with a RequiredIf attribute: https://stackoverflow.com/questions/52321148/conditional-validation-in-mvc-net-core-requiredif

But this introduces a jquery depency.  We would at least want to only introduce this conditionally not globally across all pages.

And even then, it gets weird in that it would have to be a hidden model value, that the user could override if they were clever enough.

**Comment by adelikat** [comment]
Hmm, had a simpler idea.  What if we simply auto-fill the revision message if it is a homepage? a default message such as "Homepage update"

**Comment by vadosnaprimer** [comment]
Or just `Update`.
