### ISSUE TITLE
Replace ListAllMovies

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#276]
1) we want a Game page, that would list all game (or game groups?) organized by system.
2) Remove ListAllMovies during wiki import
3) Add a redirect to go to this new game page, or find a way to replace the links on the 2 pages that reference this one

**Comment by vadosnaprimer** [comment]
http://tasvideos.org/Games.html

**Comment by adelikat** [comment]
Yes you are right! That page is a better page and completely obsoletes ListAllMovies. I udpated references on the legacy site and deleted the page.  Since this isn't a page anymore, closing this issue :)
