### ISSUE TITLE
Youtube Integration

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#278]
The site syncs Publication metadata with Youtube videos.

We need to investigate and replicate this functionality

**Comment by adelikat** [comment]
Some details on what the current design idea:
1) Publishers get video upload capabilities directly to youtube (no side loading)
2) Publishers upload video unlisted
3) Publishers publish movie and provide url
4) System decides if it has access to update the movie
5) If able, it will make the video public and sync it with title, description, tags, etc
6) If a publication is edited, a similar sync will occur, on any potential url provided

No side loading, no separate apps, or authentication by the publishers will be needed

**Comment by vadosnaprimer** [comment]
There's also update needed on movie edits, like game name, branch label, description, etc. And if a movie gets obsoleted, TVC marks it as `[Obsoleted]`: https://www.youtube.com/watch?v=79lEWIjD-CA

**Comment by adelikat** [comment]
Ah, I didn't consider the obsoletion scenario, nice catch.  Not hard to do, fortunately

**Comment by adelikat** [comment]
Breaking up the remaining todos into separate tickets, so we can close this monolithic ticket:
https://github.com/adelikat/tasvideos/issues/369
https://github.com/adelikat/tasvideos/issues/370
