### ISSUE TITLE
Code tag on forum and syntax highligh options

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#284]
https://tasvideos.mistflux.net/Forum/Topics/2012?Highlight=364353&CurrentPage=2#364353

If you just use
```
[code]yeah
yeah[/code]
```
it works, but
```
[code=lua]yeah
yeah[/code
```
breaks whitespaces.

In addition, the old forum has [download code sample](http://tasvideos.org/forum/viewtopic.php?p=364353#364353) functionality if you add the filename: `[code=file.lua]yeah[/code]` which the new forum doesn't seem to have.

In the Preview window it always shows as if it only had the `code` tag and no syntax specifier.

**Comment by nattthebear** [comment]
Strange.  The problem appears to be on the JS side, syntax highlighting.  Did this ever work?
