### ISSUE TITLE
Complex code in quote authors doesn't render

### ISSUE THREAD

**Issue by nattthebear** [adelikat/tasvideos#305]
Old site: http://tasvideos.org/forum/viewtopic.php?p=503451#503451
Test site: https://tasvideos.mistflux.net/Forum/Topics/19741?Highlight=503451&CurrentPage=28#503451

What the user wrote:
```bbcode
[quote="feos"][quote="[url=http://tasvideos.org/MovieRules.html#FullCompletionCriteriaMustBeReachedThroughInGameActionsOnly]The rule[/url]"]Arbitrary code execution of ROM data, and memory corruption tricks to write to arbitrary memory are also not allowed.[/quote]
Will gaining ASE involve writing to arbitrary memory?[/quote]
```

The old site makes this into a quote block with a link to the rules as the "author".  The new site rejects this and does not parse it as bbcode at all, instead displaying it raw.

**Comment by nattthebear** [comment]
Here are some old site behaviors:

This is a quote with the text `feos wrote` not in italics:
```
[quote="feos"]test[/quote]
```

This is a quote with the text `feos wrote` in italics:
```
[quote=feos]test2[/quote]
```

This is a url:
```
[url=https://google.com]googel[/url]
```

This is not a url, and is not parsed at all:
```
[url="https://google.com"]googel[/url]
```

This is a quote with the text `The rule wrote` not in italics: **(This is the exact text given in the issue report)**
```
[quote="[url=http://tasvideos.org/MovieRules.html#FullCompletionCriteriaMustBeReachedThroughInGameActionsOnly]The rule[/url]"]Arbitrary code execution of ROM data, and memory corruption tricks to write to arbitrary memory are also not allowed.[/quote]
```

This is a quote with the text `The rule wrote` in italics:
```
[quote=[url=http://tasvideos.org/MovieRules.html#FullCompletionCriteriaMustBeReachedThroughInGameActionsOnly]The rule[/url]]Arbitrary code execution of ROM data, and memory corruption tricks to write to arbitrary memory are also not allowed.[/quote]
```

So it seems like the old site in general doesn't support, allow, or recognize `"` in tag values, except for quote which allows it, but for some reason `[quote]` with `"` and `[quote]` without `"` render differently.  (And it's not just a simple css class difference; the markup is different structurally.)

At the same time, this is mostly orthogonal to the primary issue, which is that the new parser does not allow square brackets inside tag values at all, but the old site does.  After allowing square brackets inside tag values, the new parser would then need to parse markup inside the `[quote]` tag value as full markup, handling things like urls.

**Comment by nattthebear** [comment]
@vadosnaprimer Tell me, how common is this sort of thing in the old site?  You can't do it automatically by way of the quote button; it has to be manually inserted.

**Comment by vadosnaprimer** [comment]
I do it all the time when I quote something official, be it rules or precedent submission judgments. I've seen others do it too but can't tell how often.

Yes I select the quote author in `""` and use the URL forum tag button, then I add what it links to, with `=`.

**Comment by adelikat** [comment]
To be clear, it is a manual process to add the link?

**Comment by vadosnaprimer** [comment]
Yes.

**Comment by nattthebear** [comment]
Note to self:  Look at http://tasvideos.org/forum/viewtopic.php?p=504566#504566 as an example more of the quote-quote behavior and not the embedded URL behavior.

**Comment by vadosnaprimer** [comment]
Everything seems to work!
