### ISSUE TITLE
Migrate from SQL Server to Postgres

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#306]
SQL Server isn't free for production use, and rather expensive.  We need to migrate to a free technology.  I prefer we move to postgres though mysql is an option (I just hate the tooling).

We should still have an option to use sql server for local development, and even the demo site for awhile at least, since the use of SQL Server BulkInsert speeds up the data imports tremendously

**Comment by nattthebear** [comment]
I'm looking at the `BulkInsert` feature of demo data importing right now (right now being within the next few minutes, or next few weeks).  We should be able to do something similar in postgres.

**Comment by adelikat** [comment]
We have migrated to postgres, including a pretty fast bulk importer, and a sample data generator.  The demo site has been moved over as well.  As a bonus, for local development, mssql is still an option to use.

I'm considering this issue closed
