### ISSUE TITLE
Old superscript wiki formatting not working

### ISSUE THREAD

**Issue by Zinfidel** [adelikat/tasvideos#308]
The current site's wiki formatting for superscript are double upper half brackets "⸢⸢stuff⸣⸣". You can see on this page: https://tasvideos.mistflux.net/7026S that the superscript formatting is not being applied correctly on the new site. The superscripts appear in the tables.
![image](https://user-images.githubusercontent.com/1929934/108776144-d51b5280-7516-11eb-832d-b9e91b69ba61.png)

**Comment by nattthebear** [comment]
What an awful thing.  How are you supposed to type those?

Well, not too hard to add anyway.

**Comment by Zinfidel** [comment]
I think the superscript/subscript formatting is one of the most egregious sins of the current wiki formatting system. Maybe these upper-half-bracket and lower-half-bracket (for subscript) formatting things can be locked away behind a legacy requirement of some kind?

**Comment by nattthebear** [comment]
It might be best to just implement this for now and then improve it in https://github.com/adelikat/tasvideos/issues/219 somewhere down the line.
