### ISSUE TITLE
SubmitMovie - Trying to upload a 19KB zipped .fm3, can't see the error in the box

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#336]
https://i.imgur.com/qTxKAVn.png

(.fm3 is supported by the old site)

**Comment by adelikat** [comment]
That image suggests the demo site had a very bad data import.  What you would have seen is a message telling you that the file format is not supported.  And we do not want to support .fm3 going forward.  More hassle than it is worth.  Much like .tasproj for BizHawk, one can easily export to a .fm2
