### ISSUE TITLE
Font of forum location is too tiny

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#342]
https://i.imgur.com/tv9wXGT.png

Also it'd be better to have a button sending to submission page rather than a tiny text in parentheses.

**Comment by adelikat** [comment]
The first one is dubious to request a change too, you have the same text in big letters right above it, it is redundant at best.  Also it is exactly how the old phpbb2 forum behaves.

For the 2nd piece, A button, I'm not sure about.  What do other people think?

**Comment by vadosnaprimer** [comment]
The old site has smaller font in general. In this pace it looks tiny for no reason and kinda out of place.

The text above is the topic name but not the forum location. Though the old site doesn't have the same text in 2 places close to each other. It only shows thread name in one place.
https://i.imgur.com/0fhTWOM.png

**Comment by Randomno** [comment]
https://i.imgur.com/PnERA0p.png

Thoughts?

- Navigation from <small> to <span>
- -> to → (don't think this symbol will cause issues, and -> looks particularly bad on subforums like [here](https://tasvideos.mistflux.net/Forum/Subforum/7))
- Submission header to 18px
- link text to lowercase (insignificant but thought it looked better)

**Comment by Masterjun3** [comment]
Lowercase looks bad here. Inconsistent with the title case of all the other titles on the site.

**Comment by Randomno** [comment]
Not sure what qualifies as a title but there seems to be several inconsistencies between title and sentence case.

Also using h5 instead of 18px would be consistent with the header on the submission page. It's a little bigger.

**Comment by vadosnaprimer** [comment]
I don't really think the same exact text should be present in 2 places close to each other. Since the old forum only shows which subforum we're in, and then displays the topic title separately. So I'd just do it like this (font style is already there in subforum view)

![изображение](https://user-images.githubusercontent.com/7092625/134528228-a36e5bd5-325a-45bd-a00a-8955d99cfcdb.png)

**Comment by Randomno** [comment]
Been looking into implementing this. I agree with feos's navigation change, since having the thread title in 3 different places near each other is unnecessary, but I'm not sure how best to deal with locked threads.

https://tasvideos.mistflux.net/Forum/Topics/21346

If the current thread is removed from the navigation the red border won't make sense anymore.

**Comment by vadosnaprimer** [comment]
On the old forum, "Locked" replaces the "Post" button, so the same can be done here (with red BG).

**Comment by Masterjun3** [comment]
I have it like this (before | after):
![image](https://user-images.githubusercontent.com/22375320/134768448-665e59d3-ecab-467b-b22a-e28ad208cd82.png)

(I'm currently in the process of doing a change to all titles and headers.)

**Comment by vadosnaprimer** [comment]
Looks perfect!

**Comment by Randomno** [comment]
"Submission Text" header is still unchanged which was part of the original issue. Don't know if there's any intention for a button to be added there.
