### ISSUE TITLE
When editing obsoleted by, the list looks completely unordered

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#346]
Makes it impossible to find anything
https://tasvideos.mistflux.net/Publications/Edit/4514

**Comment by adelikat** [comment]
Strange!!

It is ordered by the text of the dropdown:
.OrderBy(p => p.Text)

Running locally on windows, I get a completely ordered set.

On the demo server, it looks random
![DemoServer-ToObsoleteList](https://user-images.githubusercontent.com/1679846/131408770-afb779fc-971f-439e-ab7c-fef161dd89fd.png)

Locally:
![Local-ToObsoletedList](https://user-images.githubusercontent.com/1679846/131408869-75cde0e9-5be1-44d6-a820-874024b57ed4.png)
