### ISSUE TITLE
Looks like movie tags don't get imported from the old site.

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#349]
Only see them in the movie I manually added them to.
https://tasvideos.mistflux.net/4514M

**Comment by adelikat** [comment]
They do get imported.  Not sure what happened to the data import of the demo site this week, but the code has been built and I've seen it work on the demo server in the past

**Comment by adelikat** [comment]
Seems an importer bug was introduced in the PublicationTags step (and explains why things later in the process, like user files, were missing)

**Comment by adelikat** [comment]
Fixed
