### ISSUE TITLE
Emulator version doesn't survive publishing

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#350]
In the submission, emulator was `fceux 0.0.0`, but when published it became `EFF-ZOOKS`.
https://tasvideos.mistflux.net/7202S
https://tasvideos.mistflux.net/4514M

**Comment by fsvgm777** [comment]
It read "fceux 0.0.0" before I edited it to "EFF-ZOOKS", so this is not a bug.
