### ISSUE TITLE
HTML gets copied upon selection

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#351]
On submission page, if I select a header cell and a text cell next to it (`Emulator | fceux 0.0.0`) and copy that, here's what actually gets copied:

```
<html><body>
<!--StartFragment-->

Emulator | fceux 0.0.0
-- | --


<!--EndFragment-->
</body>
</html>

```

**Comment by nattthebear** [comment]
This is how _all_ web browsers work _all_ the time.  When you copy text from a web page, it copies a rich text format which can be interpreted in a variety of ways:  as plain text, as HTML, and possibly others.  If you examine the raw text content of the HTML format, you'll see something like this.  More reading at https://docs.microsoft.com/en-us/windows/win32/dataxchg/html-clipboard-format.
