### ISSUE TITLE
Link publication history from game pages

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#357]
It exists as a separate thing and is awesome, we just need it to be directly linked
https://tasvideos.mistflux.net/66G
https://tasvideos.mistflux.net/Games/PublicationHistory/66

Also should it show icons/flags? Sounds useful imo.

**Comment by adelikat** [comment]
Flags might be useful, please make a separate ticket, I think that can be some future task.  Closing this ticket since I added tier icons and links
