### ISSUE TITLE
Timezones are duplicated

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#358]
When editing my profile settings, I see a lot of identical timezone options
https://i.imgur.com/aZHdeil.png

**Comment by adelikat** [comment]
I thought this was sorted out :( https://github.com/adelikat/tasvideos/issues/72

**Comment by adelikat** [comment]
Showing the ID instead of the display name that is disappointingly the same on unix systems. https://github.com/adelikat/tasvideos/commit/c60ea1b525bf544b8ab6b1ebae25c07658e803d4

I think this closes this issue
