### ISSUE TITLE
Implement UserFile edit

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#361]
When I hit the Edit button, nothing happens.

I can delete them fine, tho that leads to a blank page. Looks like the empty page remains a legit link, just no content?

**Comment by meshuggahtas** [comment]
I can't edit nor delete them.

**Comment by adelikat** [comment]
Delete works fine for me, and redirects the way I would expect.

Edit doesn't work, because it never got built, renaming this ticket accordingly
