### ISSUE TITLE
Permission to edit other people's userfiles

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#366]
Where do we usually check which permissions exist on the site currently?

**Comment by adelikat** [comment]
Can you edit other people's userfiles on the old site?

**Comment by vadosnaprimer** [comment]
Yes.

**Comment by adelikat** [comment]
How critical is this? What do you do when you edit other people's movies? Do you change the file? or just the information?

**Comment by adelikat** [comment]
Marking this as day 1 critical.  It is to control potential rom links or other egregious behavior

**Comment by adelikat** [comment]
Permission to Edit a user's file already exists, and is limited to Admin and Admin Assistants, currently

**Comment by adelikat** [comment]
added permission to forum moderator, and fixed a bug where edit comment was not checking the permission (just if it was the user), delete comment was working as expected
