### ISSUE TITLE
Publication title font is smaller than userfile's

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#367]
https://tasvideos.mistflux.net/3273M
https://i.imgur.com/VSOmTvT.png
looks small, especially on gray, especially compared to
https://tasvideos.mistflux.net/UserFiles/Info/5750263849610264
https://i.imgur.com/jeIDqme.png

I feel they should be both the size of the latter.

**Comment by adelikat** [comment]
Is this a thing you can do on the current site??

**Comment by vadosnaprimer** [comment]
About the same on the current site
https://i.imgur.com/IZjZVjO.png
https://i.imgur.com/UYfEaXU.png

**Comment by TiKevin83** [comment]
fixed in #380
