### ISSUE TITLE
Preferred Pronouns (Imported from User Gender symbols)

### ISSUE THREAD

**Issue by Spikestuff** [adelikat/tasvideos#373]
Probably not a high priority, but it's worth noting at least.
The symbols that are next to people's accounts are just currently missing quick example:
![image](https://user-images.githubusercontent.com/12412764/131822202-9690807b-7374-46d6-a7c9-c13309a64a18.png) ![image](https://user-images.githubusercontent.com/12412764/131822319-0deb7321-55aa-4437-bfbf-59eaa4065ce0.png)

**Comment by noxxaa** [comment]
It has been suggested to replace the gender icon field with a pronouns field (he/him, she/her, they/them, etc.), which would give people more flexibility in being able to express themselves.

**Comment by SamsaraTAS** [comment]
> It has been suggested to replace the gender icon field with a pronouns field (he/him, she/her, they/them, etc.), which would give people more flexibility in being able to express themselves.

Recommending:
he/him
she/her
they/them
he/they
she/they
any
other

I think we've discussed a username change request form, perhaps we could have the same for custom pronouns? I'm not quite comfortable leaving it as a write-in, there's a little too much potential for abuse if it's left open.

**Comment by adelikat** [comment]
I honestly would like to do exactly this, and replace what we have

**Comment by meshuggahtas** [comment]
List based input
- Users able to select from possible pronouns. Easy to modify selection later by devs.

Text based input
- Users able to input any text. Hard to restrict bad behaviour. How much? What letters?
- Users might (for example me) would use this as a royal/noble title like Your Highness / Majestical
