### ISSUE TITLE
UI Moan: Obsoletion Message for publication box should be inside box

### ISSUE THREAD

**Issue by scrimpeh** [adelikat/tasvideos#378]
[Image Link](https://imgur.com/a/aweYUOk)

Which movie is obsoleted? The subtle grey line isn't clear enough to distinguish it, which makes it pretty confusing.

I'd suggest putting the obsoletion message somewhere in the movie box. The header might be a good place for it.

**Comment by adelikat** [comment]
This is a legit point

**Comment by TiKevin83** [comment]
possibly fixed in #380

**Comment by TiKevin83** [comment]
This obsoletion message is in multiple places in the codebase, still needs additional cleanup
