### ISSUE TITLE
Submissions: Can't view page of new submission due to InvalidOperationException

### ISSUE THREAD

**Issue by scrimpeh** [adelikat/tasvideos#381]
See: https://tasvideos.mistflux.net/7202S

If the submission has been wiped by the time someone gets around to it, I can resubmit.

I submitted a new movie through the submission form. As I try to view it, I get an error page saying "InvalidOperationException: Nullable object must have a value.".

I don't have a setup ready to verify, but I guess [something in here](https://github.com/adelikat/tasvideos/blob/master/TASVideos/Pages/Submissions/View.cshtml.cs#L52-L85) might be null unexpectedly?

**Comment by Spikestuff** [comment]
Going to go out on a whim and say it's because the demo site hasn't updated to match what current site has yet.
This is also reflected on current Publication being DK64 and not SSBB.
(This error can be spotted in other current submissions after that one)

**Comment by Noxxaa** [comment]
> Going to go out on a whim and say it's because the demo site hasn't updated to match what current site has yet.
> This is also reflected on current Publication being DK64 and not SSBB.
> (This error can be spotted in other current submissions after that one)

He made a new submission on the test site, and specifically that submission link is breaking. Later submission IDs just result in a 404 error.

In fact, it seems there are two submissions, 7202S and 7204S. 7203 also gives a 404 error.

**Comment by scrimpeh** [comment]
I resubmitted the movie because I thought it hadn't gone through the first time, resulting in IDs 7202 and 7204. The gap between them is pretty interesting in its own regard.

**Comment by adelikat** [comment]
Keep in mind, all this will be wiped Sunday anyway.  As such, we should be careful about links to demo generated data in tickets

**Comment by scrimpeh** [comment]
[Seems to have been fixed.](https://tasvideos.mistflux.net/7208S)

I'm closing the issue.
