### ISSUE TITLE
Implement relative time display for posts (and other things)

### ISSUE THREAD

**Issue by Masterjun3** [adelikat/tasvideos#393]
Practically all of the modern Internet shows `1 hour ago` instead of `2021-09-06 22:33:44` for time displays. It usually shows the precise timestamp when hovering or clicking on the relative time.

Of course, the trivial solution of dynamically changing the webpage would run into problems e.g. with caching.
So I assume the solution here would be a javascript one. Just serving the date in ISO 8601 format and then running the javascript over the tags to convert it, I think.

**Comment by nattthebear** [comment]
> Of course, the trivial solution of dynamically changing the webpage would run into problems e.g. with caching.

The site has a lot of dynamic content on it and there's no setup in place for making any of that caching friendly, so we should be able to just do this.

**Comment by Masterjun3** [comment]
Implemented in bd46d86a8ad45db7509cdf6ff66e6a837a24f003.
