### ISSUE TITLE
Implement Dark Mode

### ISSUE THREAD

**Issue by TiKevin83** [adelikat/tasvideos#397]
now that we've migrated to bootstrap 5 we can do the following:
use `media prefers-color-scheme: dark` to theme the site automatically based on the presence of dark mode
set different color variables on `:root {}` for the dark theme
add dark icon and change out light/dark icon visibility in the dark theme
add "dark mode" button in the header or footer to force toggle light/dark themes

**Comment by nattthebear** [comment]
> add "dark mode" button in the header or footer to force toggle light/dark themes

Why?  If we're keying off of `prefers-color-scheme`, choosing themes is then a UA matter.

**Comment by TiKevin83** [comment]
> > add "dark mode" button in the header or footer to force toggle light/dark themes
> 
> Why? If we're keying off of `prefers-color-scheme`, choosing themes is then a UA matter.

When I've used the media query before I've gotten a ton of comments along the lines of "I don't see it" and "I have my system in dark mode but prefer the light theme," having a button to toggle is a nice fallback for older OSes/niche users
