### ISSUE TITLE
Broken Diff and Delete buttons on 'Edit History For User' pages

### ISSUE THREAD

**Issue by bigbass1997** [adelikat/tasvideos#408]
On pages such as https://tasvideos.mistflux.net/Wiki/EditHistory/Bigbass or https://tasvideos.mistflux.net/Wiki/EditHistory/adelikat (or seemingly any user), both the Diff or Delete buttons don't appear to do anything.

Firefox's debug/network tool shows data being downloaded upon clicking Diff, but nothing changes on the page, nor are you redirected. The Delete button instead throws an error into the console.

**Comment by adelikat** [comment]
Fixed.  Delete button was due to the boostrap 5 upgrade.
The diff button was working it just shows at the bottom of the page.  Moved it up to the top of the page to match the PageHistory page behavior
