### ISSUE TITLE
Userfiles uploading and downloading

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#411]
Upload page says
```
Used: 122,00 MB Limit 50,00 MB
244,9%
```

and upon uploading it says
```
File exceeds your available storage space. Remove unecessary files and try again.
```

Old site says
```
Quota left: 35736kB
```

**Comment by meshuggahtas** [comment]
It's probable that the old site has different limits for different users.

My stats between old site and new site is OK.

Please try deleting this 2 userfile, should be enough to get under the new 50 MB limit

https://tasvideos.mistflux.net/UserFiles/Info/63067350973390167
https://tasvideos.mistflux.net/UserFiles/Info/54113116244198159

**Comment by adelikat** [comment]
I lowered the limit

**Comment by vadosnaprimer** [comment]
The demo site doesn't accept compressed files and says it compresses them itself, so somehow those imported userfiles will have to be compressed by the demo site at some point. For [text-based movies](http://tasvideos.org/userfiles/info/54113116244198159), that saves tremendous amount of space (I know I should have compressed them, but it wasn't required by the old site so I didn't bother).

**Comment by adelikat** [comment]
The importer automatically compresses all user files

**Comment by vadosnaprimer** [comment]
It still says 32MB on new site https://tasvideos.mistflux.net/UserFiles/Info/54113116244198159

If even after compression all my userfiles are 144% over the limit, I can't say I agree with that limit. I don't even upload movies that often, but often it's for things I judge, so they're meant to persist over the years. Removing WIPs is also not ideal because they may serve as valuable insight for some game. I'd definitely remove those 20-30MB ones because they are not needed anymore, but when compressed they are tiny, below 200KB.

**Comment by vadosnaprimer** [comment]
Reopening to get some actual discussion. It's not my ego, it's a functional obstacle that needs to be resolved one way or the other.

**Comment by Masterjun3** [comment]
I just uploaded a 7MB .dsm file (easily compressed), it took away 7MB of my storage, and upon download it gave me a 3.5MB .dsm file **which was cutoff -> data loss**.

**Comment by adelikat** [comment]
Data loss is pretty bad, not sure what happened there, but needs to be looked into

**Comment by Masterjun3** [comment]
Relevant stackoverflow answer: https://stackoverflow.com/a/7343623
In the Compress function (in FileService.cs) there needs to be a Dispose (or I suppose a DisposeAsync) of the gzip stream before doing the ToArray.
The answer also says we need the Dispose for the decompression (which is done in UserFiles/Info.cshtml.cs), but I don't know enough about that.

**Comment by vadosnaprimer** [comment]
```
Used: 5,00 MB Limit 50,00 MB
10,7%
```
It's good now!
