### ISSUE TITLE
Long and complex legacy passwords might not work

### ISSUE THREAD

**Issue by meshuggahtas** [adelikat/tasvideos#413]
Original submitter has long and complex password on tasvideos.org which doesn't works on demo site.

It can be used to log in to the tasvideos.org forums but not for the tasvideos.org currently active site.

http://tasvideos.org/forum/viewtopic.php?p=508515#508515

**Comment by adelikat** [comment]
The limit on the new site is 100 characters, but that is for setting a new password. Anything that works on the forum in the old site is what is used on the new site.  So I do not see how this could effect migration of user data.

This issue tracker is not for reporting issues with the current (legacy) code base.

**Comment by meshuggahtas** [comment]
"For reference, the password was 64 characters long and contained spaces, dashes, brackets and ISO 8859-1 characters."

http://tasvideos.org/forum/viewtopic.php?p=508599#508599
