### ISSUE TITLE
Wiki anchor URLs are different which breaks existing anchor links

### ISSUE THREAD

**Issue by Randomno** [adelikat/tasvideos#446]
http://tasvideos.org/MovieRules.html#FullCompletionCriteriaMustBeReachedThroughInGameActionsOnly
[https://tasvideos.mistflux.net/MovieRules.html#Fullcompletioncriteriamustbereachedthroughin-gameactionsonly.](https://tasvideos.mistflux.net/MovieRules.html#Fullcompletioncriteriamustbereachedthroughin-gameactionsonly.)

Not sure if the intention is to keep it this way and change links in articles accordingly. This also affects some forum post links.

**Comment by nattthebear** [comment]
> This also affects some forum post links.

I'm not sure what you mean with this.

**Comment by nattthebear** [comment]
I made some fixes for this in cbfac871d38f7ac130c858be585575fd1d41c0c7.  Let me know if there are any other discrepancies.

**Comment by Randomno** [comment]
> I'm not sure what you mean with this.

Some forum posts also use these anchor links. It's not really relevant.

**Comment by nattthebear** [comment]
Closing, feel free to reopen if any issues persist

**Comment by Randomno** [comment]
Current site omits leading A and The:

http://tasvideos.org/MovieRules.html#MovieMustBeGood
http://tasvideos.org/MovieRules.html#SpeedOrientedMovieMustBeatAllExistingRecords

Couldn't find any other words it omits.

Some more obscure behaviour that I don't know if it replicates or is worth adding:

If there are multiple headings of the same name, future headings will be _2, _3, etc.

If there are multiple headings starting in "A" or "The" with the rest the same, e.g. "The foo" and "A foo", the first one will become "Foo" and the second "AFoo".

**Comment by nattthebear** [comment]
I'm not committed to 100% parity here, but if the old site avoids duplicates, we probably should too.

**Comment by nattthebear** [comment]
OK, fixed those as well.

**Comment by Randomno** [comment]
I think this issue is slightly different but related. Wouldn't say it's very important though.

Links in headings without a custom description are parsed differently.

http://tasvideos.org/wiki.exe?page=SandBox&rev=555
https://tasvideos.mistflux.net/SandBox

(the last heading there works the same)

Other changes seem to work fine.

**Comment by nattthebear** [comment]
I don't see anything there that concerns me enough.  We'll never be perfectly matching on this feature.
