### ISSUE TITLE
Some userfiles are 0 bytes when trying to download them

### ISSUE THREAD

**Issue by Masterjun3** [adelikat/tasvideos#447]
Example: https://tasvideos.mistflux.net/UserFiles/Info/55978485290185952

Most likely cause of this is the compression code either compressing the file or leaving it uncompressed if it's smaller that way, but then the decompression code always expects the file to be compressed.

**Comment by adelikat** [comment]
code now takes into account whether the file is actually compressed.  However, that still does not fix this example since the database says it is compressed, for investigation needed

**Comment by Masterjun3** [comment]
All my userfiles work now.
Maybe after the code fix a database reimport resolved it.
Feel free to close this @adelikat if you don't have anything else to look into here.

**Comment by nattthebear** [comment]
Please reopen, or open a new issue, if any new problems are seen with userfiles.
