### ISSUE TITLE
"!" does not work to suppress links in wiki markup

### ISSUE THREAD

**Issue by SandTAS** [adelikat/tasvideos#453]
The [documentation for links](http://tasvideos.org/TextFormattingRules.html#ReferencesLinks) says:
> You can suppress automatic hyperlink parsing by preceding the link with a ‘!’, e.g. !http://not.linked.to/.

Here is an example of `!` not working in a preformatted code block, though it doesn't work in other contexts either. The URL becomes a link and the `!` appears in the output.
https://tasvideos.mistflux.net/GameResources/DOS/CaptainComic#Resources
<blockquote>
<pre>
git clone !<a href="https://www.bamsoftware.com/git/comic.git">https://www.bamsoftware.com/git/comic.git</a>
cd comic/tas/
</pre>
</blockquote>

I expected it to look like this:
http://tasvideos.org/GameResources/DOS/CaptainComic.html#Resources
<blockquote>
<pre>
git clone https://www.bamsoftware.com/git/comic.git
cd comic/tas/
</pre>
</blockquote>

**Comment by nattthebear** [comment]
Pretty sure I just didn't build this -- it's yet another random markup nuance.
