### ISSUE TITLE
Forum [img=width] markup does not enforce a width 

### ISSUE THREAD

**Issue by SandTAS** [adelikat/tasvideos#455]
This markup:
```
[img=600]https://www.bamsoftware.com/comicrando/comicrando-logic-map.svg[/img]
```
in the old site is scaled to 600px wide, but in the new site has its full size.

* https://tasvideos.mistflux.net/Forum/Topics/21916?CurrentPage=1#495817
* http://tasvideos.org/forum/viewtopic.php?p=495817#495817

**Comment by nattthebear** [comment]
We handle `0x0` for width x height but not just width.  @SandTAS Do you know if `[video]` is the same way?

**Comment by SandTAS** [comment]
I did not find an example of a [video] with a width or width/height, but it looks like the parser for video uses the same `TryParseSize` as img does.
* https://github.com/adelikat/tasvideos/blob/c79da261cc59bb5d739cc9aba2fa58eeec76546b/TASVideos.ForumEngine/Node.cs#L257
* https://github.com/adelikat/tasvideos/blob/c79da261cc59bb5d739cc9aba2fa58eeec76546b/TASVideos.ForumEngine/Node.cs#L403
* https://github.com/adelikat/tasvideos/blob/2250d6c2ab759164c7633b897f9f8af625a5999b/TASVideos.ForumEngine/Video/WriteVideo.cs#L15-L20

**Comment by nattthebear** [comment]
Yeah, I'm wondering how [video] works on the old site

**Comment by nattthebear** [comment]
`[video]` is _not_ the same way; the old site ignores the width value if no height is provided.

**Comment by SandTAS** [comment]
Here I found a post with `[video=WxH]`:
http://tasvideos.org/forum/viewtopic.php?p=478286#478286
```
[video=640x384]https://archive.org/download/megamanpc-tas-1_48_083/megamanpc-tas-1_48_083-soundhack.mp4[/video]
```
