### ISSUE TITLE
Feature request: borders in forum tables

### ISSUE THREAD

**Issue by vadosnaprimer** [adelikat/tasvideos#456]
Very few people know this feature exists, but when they use it, it becomes incredibly hard to figure out the columns. It'd be very helpful if there were borders around cells.

https://tasvideos.mistflux.net/Forum/Topics/21916?Highlight=500037&CurrentPage=1#500037

Old site doesn't have them either

http://tasvideos.org/forum/viewtopic.php?p=500037#500037

**Comment by SandTAS** [comment]
I don't know what the difference is, but in the automatic forum post made from a submission, the old site renders tables with borders and a different background color for headings. Example:
* http://tasvideos.org/6192S.html
* http://tasvideos.org/forum/viewtopic.php?p=478292#478292

It looks decent in the rewrite:
* https://tasvideos.mistflux.net/6192S
* https://tasvideos.mistflux.net/Forum/Topics/20675

**Comment by nattthebear** [comment]
The generated html looks like it should support useful styling so this is just a styling feature request.

@SandTAS The forum post containing submission text is a completely different beast, because that's wiki markup and not forum markup.
