### ISSUE TITLE
Rating input not sanitized

### ISSUE THREAD

**Issue by meshuggahtas** [adelikat/tasvideos#465]
You can rate even with negative values if you edit html. Every user input "must" be sanitized.

1. Go to a movie rate page
2. Edit an option value to -44
3. Rate

**Comment by meshuggahtas** [comment]
I don't really know if there was a new change, but currently the rating doesn't works with .5 values only whole numbers.

```
The value '9.5' is not valid for Tech Rating.
The value '0.5' is not valid for Tech Rating.

The value '9.5' is not valid for Entertainment Rating.
The value '0.5' is not valid for Entertainment Rating.
```

**Comment by adelikat** [comment]
I'm not seeing this error.  I can rate with all of these values just fine.  I'm using /Publications/Rate/[movieid]

**Comment by meshuggahtas** [comment]
Still affects me.

My notes:
- Looks like only my account has this particular problem.
- I have voted erroneous values in the past on the demo site.
- I'm unable to try with other account through registering on the demo site (email doesn't comes probably intentional).
- I'm unable to try it on local server, I get Internal Server Error after pulling latest commit master branch and trying to start Dev Postgresql Sample Data.

Here is a screenshot of not able to vote .5 values:

![Képkivágás2](https://user-images.githubusercontent.com/31288337/136155388-ac9451b2-a2e2-4948-bda9-3033eb1b968c.PNG)
 
Only thing I can try is register to the production site (to have double account in my possession) and test it tomorrow. Not sure this should be the way to test/debug my problem.

**Comment by meshuggahtas** [comment]
We found the culprit, not sure what's the difference between me and others.

- I have dot separated values (0.5, 1.5, ... 9.5) in the dropdown, which doesn't works for me
![dropdown](https://user-images.githubusercontent.com/31288337/136160309-27139a55-d980-4235-ae22-c6ce579b06c8.PNG)

- Editing HTML to rate 0,5 works for me


So... the only place I have dot (.) separated values is while choosing a rating option from the dropdown. On all other places of the website, I have comma separated values.

(Thanks fsvgm777)

**Comment by meshuggahtas** [comment]
Back to the main issue, the following rates are still possible to give:
0,001
0,0001

My suggested solution is still the following (which I forgot to write down yet):
- Only accept a list of values
- Check it from server-side

Example:
- TASVideos want to use the following rating numbers: 0, 0.5, 1, 1.5....
- Make a constant readonly list of values consisting the exact same numbers
- After posting a rate, the server logic should try to convert the input of user to a number from this list
- If it doesn't works, return error.
