### ISSUE TITLE
inconsistent Publication list on forum profiles

### ISSUE THREAD

**Issue by ViGadeomes** [adelikat/tasvideos#467]
As seen here on the new site :
![Capture](https://user-images.githubusercontent.com/56033116/134546974-8568f73e-4150-446b-b832-a2205c1e4654.PNG)
We have a link to all active movies of a user and another that should link to all obsoleted movies of the user but link to all movies published of the user instead. 

For more consistency, we should change the "Obsolete" link to only the ones that have been obsoleted and a new one named "All" for example that list them alltogether like the current "Obsolete" one does.

**Comment by adelikat** [comment]
This is the same behavior we have always had

**Comment by vadosnaprimer** [comment]
Old site's wording is "same but including obsoleted". Here the wording makes it look like the link it so obsoleted only, and it shows their count properly, but actual link is to all movies *including* obsoleted, and their actual count is different.

[My profile](https://tasvideos.mistflux.net/Users/Profile/feos) has `5 obsolete` which links to [17 movies](https://tasvideos.mistflux.net/Movies-Author4742-obs) that *include* obsoleted.
