### ISSUE TITLE
/Search.html gives "Unknown module wikisearch"

### ISSUE THREAD

**Issue by SandTAS** [adelikat/tasvideos#468]
These URLs lead to a search page as I expect:
* https://tasvideos.mistflux.net/Search
* https://tasvideos.mistflux.net/search

But the URL with .html (corresponding to http://tasvideos.org/Search.html) gives an "Unknown module wikisearch" error. It looks like it is because "Search" is an actual wiki page, not a dedicated search page.
* https://tasvideos.mistflux.net/Search.html

(Incidentally, lowercase [search.html](https://tasvideos.mistflux.net/search.html) leads to PageNotFound.)

One way to deal with this would be to redirect /Search.html to /Search.

**Comment by adelikat** [comment]
fixed by not importing the search wiki page
