### ISSUE TITLE
Subpages modeul - nest subpages

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#47]
nest sub pages of subpages nicer
something like:
<ul>    
     <ul>HomePages/adelikat</ul>
         <li>HomePages/adelikat/AllPlatformsChallenge</li>
         <li>HomePages/adelikat/EmptyQueue</li>
    </ul>
<ul>

**Comment by Randomno** [comment]
This may be a separate issue but it would be nice to list all sub-sub-pages like this, rather than just the first couple.

![](https://i.imgur.com/GE5xajh.png)
