### ISSUE TITLE
Forum markup does not recognize `[url URL]text[/url]`

### ISSUE THREAD

**Issue by SandTAS** [adelikat/tasvideos#472]
The old BBCode parser recognizes two forms of `[url]` links with link text:
* `[url=http://example.com]text[/url]`
* `[url http://example.com]text[/url]`

The rewrite recognizes the version with an equals sign, but not the one with a space.

This post looks good:
https://tasvideos.mistflux.net/Forum/Topics/21916?CurrentPage=1#500262 ([old site link](http://tasvideos.org/forum/viewtopic.php?p=500262#500262))
```
[url=https://wiki.osdev.org/Programmable_Interval_Timer]programmable interval timer[/url]
```

This post has broken rendering:
https://tasvideos.mistflux.net/Forum/Topics/20675?Highlight=478546&CurrentPage=1#478546 ([old site link](http://tasvideos.org/forum/viewtopic.php?p=478546#478546))
```
[url https://archive.org/details/megamanpc-tas-1_47_298/megamanpc-tas-1_47_298-soundhack-30fps.mp4]30 fps encode[/url]
```

**Comment by nattthebear** [comment]
Why is this a thing?  What is gained with this alternate syntax? 😕 

I hate bbcode

**Comment by vadosnaprimer** [comment]
We gain people trying to use other tags the same way and getting broken posts.

**Comment by MemoryTAS** [comment]
Seems other tags might behave similarly on old site. I've only tested wiki so far but it behaves the same way.

**Comment by adelikat** [comment]
Gross.
