### ISSUE TITLE
`[video]` does not render a player for archive.org links

### ISSUE THREAD

**Issue by SandTAS** [adelikat/tasvideos#473]
This post has a video player in the old site but not the new:
* http://tasvideos.org/forum/viewtopic.php?p=478286#478286
* https://tasvideos.mistflux.net/Forum/Topics/9446?CurrentPage=2#478286

The markup is
```
[video=640x384]https://archive.org/download/megamanpc-tas-1_48_083/megamanpc-tas-1_48_083-soundhack.mp4[/video]
```

Compare to a youtube.com link, which renders a player in the old and new sites:
* http://tasvideos.org/forum/viewtopic.php?p=508360#508360
* https://tasvideos.mistflux.net/Forum/Topics/8210?CurrentPage=30#508360

```
[video]https://www.youtube.com/watch?v=DREo1WHWCjQ[/video]
```

**Comment by nattthebear** [comment]
The system has specific handlers for each video site it understands how to embed.  The new system simply doesn't have one for archive.org, so we have to build it.

**Comment by SandTAS** [comment]
I guess there are two things to consider:

1. Should `[video]` work with generic .mp4, .webm, etc. links, whether hosted at archive.org or anywhere else? (The old forum may be using a generic handler rather than something specifically for archive.org, I'm not sure.)
2. If there's a specific handler for archive.org, they have a nice [iframe embed feature](https://archive.org/help/video.php) similar to the [youtube embed](https://github.com/adelikat/tasvideos/blob/2250d6c2ab759164c7633b897f9f8af625a5999b/TASVideos.ForumEngine/Video/WriteVideo.cs#L49). The most convenient way for it to work would probably be to use an archive.org/details URL rather than an archive.org/download URL. E.g.,
   ```
   [video]https://archive.org/details/jaws-tas-spacecolonizer[/video]
   ```
   For items that contain more than one video file, it should be possible to specify which one should be embedded. E.g.,
   ```
   [video]https://archive.org/details/megamanpc-tas-1_48_083/megamanpc-tas-1_48_083-soundhack.mp4[/video]
   ```

**Comment by nattthebear** [comment]
The new code is all special embed handlers, so I added one for Archive.org.

**Comment by SandTAS** [comment]
Thanks, 569eda0a21af8da0b4bbdae7e8f748df8f3806b1 looks good. Ideally, though, it would recognize a path prefix of `"/details/"` as well as `"/download/"`. The [/details page](https://blog.archive.org/2011/03/31/how-archive-org-items-are-structured/) is the default page you get in the URL bar when you are viewing items on archive.org. I think I only used a /download .mp4 URL in the old forum because it did not have a rule for archive.org embeds.

**Comment by nattthebear** [comment]
> Ideally, though, it would recognize a path prefix of "/details/"

Done.

> Should [video] work with generic .mp4, .webm, etc. links

Maybe.  File that as a separate issue if there's demand.
