### ISSUE TITLE
Incorrect termination of forum `[list=1][/list]` markup

### ISSUE THREAD

**Issue by SandTAS** [adelikat/tasvideos#474]
The numbered list in this post renders correctly in the old site but not the new:
* http://tasvideos.org/forum/viewtopic.php?p=495817#495817
* https://tasvideos.mistflux.net/Forum/Topics/21916?CurrentPage=1#495817

Notice, in point 5, the text `[/list:o]`, and that the remainder of the post is indented as part of the list item.

The markup is
```
[list=1][*]Automatically assign a lower-bound cost to all edges.
[*]Set [i]P[/i] to be a shortest path in the virtual graph, given current bounds on edge costs.
[*]If every edge in [i]P[/i] has already been measured, exit. This is the route.
[*]Otherwise, manually measure one or more of the edges in [i]P[/i] and update edge costs.
[*]Go to step 2.[/list]
```

**Comment by nattthebear** [comment]
I haven't looked into this yet, but tagging as 2.1 because this may need initial import processing.
