### ISSUE TITLE
Unable to edit my own post

### ISSUE THREAD

**Issue by Masterjun3** [adelikat/tasvideos#480]
Example post I'm trying to edit: https://tasvideos.mistflux.net/Forum/Posts/491214#491214
I see the Edit button appear, but when I press it I get redirected to /Account/AccessDenied (on both demo site and my local site).

**Comment by MemoryTAS** [comment]
Welp, turns out Masterjun can only edit posts if they're the latest in the thread. #433 only the edit button was made to show, but the actual permissions to edit older posts was not granted.
