### ISSUE TITLE
Publisher ID retrieved from newest publication edit rather than oldest

### ISSUE THREAD

**Issue by Randomno** [adelikat/tasvideos#484]
Example: https://tasvideos.mistflux.net/7162S

The publisher is Zinfidel, but since CasualPokePlayer made the most recent [edit to the movie](https://tasvideos.mistflux.net/Wiki/PageHistory?path=InternalSystem%2FPublicationContent%2FM4493) they are listed as the publisher.

**Comment by Randomno** [comment]
Doesn't seem fixed?

**Comment by adelikat** [comment]
Won't take effect until the next data deploy, which will be Sunday
