### ISSUE TITLE
Request: Publication date in publication history

### ISSUE THREAD

**Issue by Randomno** [adelikat/tasvideos#486]
![Example](https://i.imgur.com/nQONUVg.png)

Somewhat related that I noticed while doing this, the current movie link has the class `font-weight-bold font-italic border border-info p-1`, but does not appear emboldened or italicised. Am I misunderstanding what this does?

**Comment by Masterjun3** [comment]
The font stuff is because it was renamed from bootstrap 4 to 5. Should be easily fixed.
