### ISSUE TITLE
Video module overflows screen width on mobile

### ISSUE THREAD

**Issue by coolkirby2000** [adelikat/tasvideos#490]
On a mobile device in portrait mode, video modules (i.e. YouTube) extend past the right edge of the screen. You have to scroll or zoom out to see the whole video. The Android device's resolution is 1080x2220, and the iPhone's is 1080x1920.

Android Chrome (latest): https://imgur.com/LaQvZmX
Android Firefox (latest): https://imgur.com/fkKWRbi
iOS Safari 14.4.2: https://imgur.com/xeEG7KA

This might be solved by giving video modules a max-width of 100% within a forum post or submission text. Though, it's been a while since I've coded in CSS.

As a side note, the FrameRate field on a submission also overflows to the right, in the above pictured submission and also others like 7200S (SNES Pitfall).
Text overflow on 7216S: https://imgur.com/7zbr8xp

**Comment by Masterjun3** [comment]
Yeah I fixed this for the forum image and video embeds. Forgot the wiki though. Will do.
