### ISSUE TITLE
Gruefood subforum sorts empty old threads at the beginning

### ISSUE THREAD

**Issue by coolkirby2000** [adelikat/tasvideos#491]
The Gruefood subforum has approximately 60 empty threads from the mid-2000s listed first, right under the stickied thread that links to Gruefood Delight. It may be a sorting issue, as the most recent threads like Wii Spider-Man 4 and N64 Harvest Moon do not appear until the second page. The empty threads also have a text glitch at the bottom of each: "Showing 1 - 0 of 0".

**Comment by adelikat** [comment]
So a few fixes were done here
1) fix the sorting so that topics with no posts wont' be first (but this should never happen if the data is correct)
2) Add in a TVA post to these specific topics so they can properly display with a poll and ability to post
