### ISSUE TITLE
Internal Server Error upon viewing forum threads

### ISSUE THREAD

**Issue by MemoryTAS** [adelikat/tasvideos#493]
Upon viewing any forum thread the following error gets displayed:

`JsonReaderException: Input string '12.590182141270546' is not a valid integer. Path '', line 1, position 18.

    Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, char firstChar, int initialPosition)
    Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
    Newtonsoft.Json.JsonTextReader.ReadAsInt32()
    Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, bool hasConverter)
    Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, bool checkAdditionalContent)
    Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    Newtonsoft.Json.JsonConvert.DeserializeObject(string value, Type type, JsonSerializerSettings settings)
    Newtonsoft.Json.JsonConvert.DeserializeObject<T>(string value, JsonSerializerSettings settings)
    TASVideos.Core.Services.Cache.RedisCacheService.TryGetValue<T>(string key, out T value) in RedisCacheService.cs

    				value = JsonConvert.DeserializeObject<T>(data) ?? default!;

TASVideos.Core.Services.PointsService.AverageNumberOfRatingsPerPublication() in PointsService.cs

    			if (_cache.TryGetValue(AverageNumberOfRatingsKey, out int playerPoints))

System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
TASVideos.Core.Services.PointsService.PlayerPoints(int userId) in PointsService.cs

    			var averageRatings = await AverageNumberOfRatingsPerPublication();

System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
TASVideos.Pages.Forum.Topics.IndexModel.OnGet() in Index.cshtml.cs

    				post.PosterPlayerPoints = await _pointsService.PlayerPoints(post.PosterId);

Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+GenericTaskHandlerMethod.Convert<T>(object taskAsObject)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+GenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
TASVideos.Extensions.ApplicationBuilderExtensions+<>c+<<UseMvcWithOptions>b__4_0>d.MoveNext() in ApplicationBuilderExtensions.cs

    				await next();

Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
TASVideos.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context, IWebHostEnvironment env, ILogger<ErrorHandlingMiddleware> logger) in ExceptionHandlingMiddleware.cs

        				await HandleExceptionAsync(context, ex, env, logger, _next);
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by nattthebear** [comment]
@adelikat Seems to be redis related?

**Comment by MemoryTAS** [comment]
closed by 9a28f441aabe26c09c411625d55428265f95b01e
