### ISSUE TITLE
Awards pages needs improvements

### ISSUE THREAD

**Issue by meshuggahtas** [adelikat/tasvideos#507]
Live site: http://tasvideos.org/Awards/2007.html
Demo site: https://demo.tasvideos.org/Awards/2007

Differences:
- Demo site doesn't shows submission cards, only links. Might be OK.
- 2.1.303 FIXED ~~Demo site Publication Awards are in a stair placement, should be vertical.~~
- Demo site User Awards should be formatted somehow. Currently it's in 2 columns on the left side, leaving many unused area on the right side.

Target milestone: 2.1

(edit: changed demo site link + Demo site Publication Awards stair placement fixed with similar 2 columns on left side as User Awards)

**Comment by adelikat** [comment]
Putting milestone 2.1 for the "stair placement" bug, and for any better formatting.

I don't want to put the publication module on this page, if that is okay
