### ISSUE TITLE
Wiki - UI to diff non-consecutive revisions

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#51]
Right now the history page only has quick diff buttons that diff the current revision with the previous.

We want to diff between non-consectutive reivsions too.
The server-side and url scheme already support this:
/Wiki/DiffData?path=GameResources&fromRevision=1&toRevision=132
But we need to add ui capabilities for this

**Comment by vadosnaprimer** [comment]
And it's very important to allow opening such diffs as new pages. Going back and forth after every unsatisfying lookup is extremely annoying.

**Comment by nattthebear** [comment]
Would making it a link (and not a button) be sufficient for that?  Then you can use middle click or whatever your UA allows to open it in a new window if you prefer.

**Comment by vadosnaprimer** [comment]
Middle-click is the main usage I have for the current engine. Middle-clicking on a button indeed feels weird.

On the main site, Recent Changes show such edits as diffs and those are links, perfectly usable. History pages only show a button, and you can't open the result in a new windows, which is very limiting.

I think making them simple links is the way to go.

**Comment by nattthebear** [comment]
Original objective complete.  Can't open diff in new page because it's ajaxing onto the current page.  Open another ticket if you really want that.
