### ISSUE TITLE
Some textboxes are white in dark mode

### ISSUE THREAD

**Issue by fsvgm777** [adelikat/tasvideos#516]
Some textboxes, like in the publication form, have a white background, making the text unreadable. Here's a screenshot illustrating the issue:

![](https://cdn.discordapp.com/attachments/738421558783246467/892849350131216394/unknown.png)

As you can see, the right text box as well as the text within are white, making it really difficult to read what's in it.

**Comment by vadosnaprimer** [comment]
Current wiki tab too

![изображение](https://user-images.githubusercontent.com/7092625/135333638-b0f21e1c-f0a0-40b1-ac2d-c1328440fd94.png)

**Comment by adelikat** [comment]
The tabs probably do need to be light, we darken in light mode to highlight, should we not lighten to highlight in dark mode?

**Comment by vadosnaprimer** [comment]
I agree with making tabs _lighter than BG_, but definitely not pure white.
