### ISSUE TITLE
IP Addresses in IP Addresses Used list do not appear to be correct

### ISSUE THREAD

**Issue by MemoryTAS** [adelikat/tasvideos#531]
When I checked my own IP it showed the individual numbers in reverse order. For example, lets say my IP address is 12.345.67.89. It showed up in the list as 89.67.345.12. Another person's address I checked was wrong as well from what they told me.

**Comment by fsvgm777** [comment]
It should be noted that only IPv4 addresses are concerned. IPv6 addresses are shown correctly.

**Comment by nattthebear** [comment]
From what I'm seeing:

Imported ipv4 addresses from the live site = backwards
ipv4 addresses used on the test site = forwards

Imported ipv6 addresses from the live site = ???
ipv6 addresses used on the test site = correct

Could others please retry, making sure you're separating reports for imported and new data?  The new site will not record an IP until you make a forum post on it, so if you have not done that you're looking solely at imported data.
