### ISSUE TITLE
Unable to run Postgres builds

### ISSUE THREAD

**Issue by meshuggahtas** [adelikat/tasvideos#536]
I'm unable to run postgres builds. 

I don't know what's missing as there are no documentation on how to configure apart from a few steps from README.md:
`Install the latest postgres and use the "Dev Postgres" profiles instead. This will better mimic deployed environments (which will always use postgres)`

Version: master branch, commit e7547969 (latest as of writing)

What I tried:
- Install latest postgresql 14 
- Tried to found but nothing, that should I create a db myself or the build will magically run a batch of commands
- Give up

**Dev Postgres (No recreate)**
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure.
 ---> Npgsql.NpgsqlException (0x80004005): Exception while connecting
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

**Dev Postgres (Sample Data)**
Browser shows nothing

**Comment by Randomno** [comment]
I had some trouble with Postgres but got it running. I think you should try creating a TASVideos db in pgAdmin, to check that you are not blocked by a password if nothing else.

**Comment by meshuggahtas** [comment]
(This is the first time I try this Postgresql technology and softwares)

Thanks for the hint, I've found the following in TASVideos/appsettings.Development.json:

Host=127.0.0.1;Port=5432;Database=TASVideos;User Id=postgres;Password=postgres;Include Error Detail=true"

I've tried manually creating this database (Host, Port (default), Db,name, Username, Password), however upon clicking on Save results in this error from pgAdmin 4:
```
Unable to connect to server:

FATAL: password authentication failed for user "postgres"
```
