### ISSUE TITLE
Ability to select movie tags and flags in the publication form.

### ISSUE THREAD

**Issue by fsvgm777** [adelikat/tasvideos#538]
On the old site, publishers can set the appropriate flags and tags in the publication form itself; however, this is as of present not possible on the new site. Currently, one has to edit the publication to be able to set flags and tags. It'd be nice to be able to add those in the publication form itself for convenience.

This is what I'm referring to, as a note (from the publication edit page)
![image](https://user-images.githubusercontent.com/14264196/136605381-e57e3948-9b28-4167-8b7f-0982b61d0956.png)

**Comment by adelikat** [comment]
This was built awhile ago and this ticket was never closed
