### ISSUE TITLE
Demo environment - IPs captured as 127.0.0.1

### ISSUE THREAD

**Issue by adelikat** [adelikat/tasvideos#540]
Creating a new ticket for this issue reported here: https://github.com/adelikat/tasvideos/issues/531 since that ticket had multiple actual issues.

What title says, probably an environment set up issue

**Comment by nattthebear** [comment]
Are we behind some sort of reverse proxy?  We may need to use a forwarded-for header

**Comment by darkpsy3934** [comment]
Yes, it is behind a reverse proxy.  The forwarded-for header isn't set, but I'm going to be correcting this issue now.

**Comment by adelikat** [comment]
The header was being passed, the app needs to use it. Fixed
